package io.github.chris2011.netbeans.plugins.breadcrumbexplorer.options;

import io.github.chris2011.netbeans.plugins.breadcrumbexplorer.utils.BreadcrumbExplorerManager;
import org.openide.util.NbPreferences;

final class BreadcrumbExplorerPanel extends javax.swing.JPanel {

    BreadcrumbExplorerPanel(BreadcrumbExplorerOptionsPanelController controller) {
        initComponents();

        chkShowAllIcons.addActionListener(e -> controller.changed());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chkShowAllIcons = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(chkShowAllIcons, org.openide.util.NbBundle.getMessage(BreadcrumbExplorerPanel.class, "BreadcrumbExplorerPanel.chkShowAllIcons.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkShowAllIcons)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkShowAllIcons)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void load() {
        // Lese die Einstellung und aktualisiere die UI
        boolean showAllIcons = NbPreferences.forModule(BreadcrumbExplorerOptionsPanelController.class)
            .getBoolean("showIconsMacFinderLike", false);

        chkShowAllIcons.setSelected(showAllIcons);
    }

    public void store() {
        NbPreferences.forModule(BreadcrumbExplorerOptionsPanelController.class)
            .putBoolean("showIconsMacFinderLike", chkShowAllIcons.isSelected());
        BreadcrumbExplorerManager.setShowIconsMacFinderLike(chkShowAllIcons.isSelected());
    }

//    public void store() {
    //        NbPreferences.forModule(BreadcrumbExplorerOptionsPanelController.class)
    //            .putBoolean("showIconsMacFinderLike", chkShowAllIcons.isSelected());
//    }
    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkShowAllIcons;
    // End of variables declaration//GEN-END:variables
}
